{"name": "test_mul[erro]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 100.0 == 200", "trace": "self = <tset_case.test_cacl_case.Testcaclcase object at 0x04591088>, get_cacl = <tset_case.cacl.cacl object at 0x04528268>, a = 100, b = 1, expect = 200\n\n    @pytest.mark.parametrize(\"a,b,expect\", getyaml()[4], ids=getyaml()[5])\n    def test_mul(self, get_cacl, a, b, expect):\n        result = get_cacl.mul(a, b)\n>       assert result == expect\nE       assert 100.0 == 200\n\ntest_cacl_case.py:54: AssertionError"}, "parameters": [{"name": "a", "value": "100"}, {"name": "b", "value": "1"}, {"name": "expect", "value": "200"}], "start": 1623311628505, "stop": 1623311628505, "uuid": "43f0c1a3-7348-4a8e-970d-07b5b434558b", "historyId": "995f5360a1358cab0915cfbfab3f5615", "testCaseId": "93bb8d81ea930ba8b69d9c38c9a9cf17", "fullName": "test_cacl_case.Testcaclcase#test_mul", "labels": [{"name": "suite", "value": "test_cacl_case"}, {"name": "subSuite", "value": "Testcaclcase"}, {"name": "host", "value": "BB-202009-DN003"}, {"name": "thread", "value": "89176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cacl_case"}]}